spring.application.name=gestion-contrats

# ===================================
# CONFIG H2 (DEV) - ACTIF
# ===================================
spring.datasource.url=jdbc:h2:mem:assurancedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2 accessible sur http://localhost:8085/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================
# CONFIG MySQL (PROD) - COMMENTÉ
# ===================================
# spring.datasource.url=jdbc:mysql://localhost:3306/assurance_db?createDatabaseIfNotExist=true
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=root
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===================================
# JPA / HIBERNATE
# ===================================
# create-drop : crée les tables au démarrage, les supprime à l'arrêt (parfait pour H2 dev)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================
# SERVEUR
# ===================================
server.port=8085
